### PR TITLE
Update Concept06_saving_variables.ipynb

### PR DESCRIPTION
**Pull request by printdhruv**

### CODE REVIEW

**Comment by BinRoot** [comment]
`savers` is never defined

**Comment by printdhruv** [comment]
Are tutorials restricted to specific version of tf and python?

**Comment by BinRoot** [comment]
Python 3 for most of it unless specified otherwise. And, TensorFlow 1.0 or above.

**Comment by printdhruv** [comment]
I will double check my code why I had to update from 'saver' to 'savers'

**Pull request closed without merging**
